version: '3.9'

services:

  nginx_proxy:
    restart: unless-stopped
    build:
      context: ../
      dockerfile: docker/nginx_proxy/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../docker/certbot/conf:/etc/letsencrypt
      - ../docker/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - backend


  certbot:
    image: certbot/certbot
    volumes:
      - ../docker/certbot/conf:/etc/letsencrypt
      - ../docker/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - backend


networks:
  backend:
    name: ${COMPOSE_PROJECT_NAME}_network
    driver: bridge
